### ISSUE TITLE
Password not found 

### ISSUE THREAD

**Issue by kngan43** [johandebeurs/alfred-mstodo-workflow#11]
I'm having the issue below shown below. The workflow worked initially when I installed it and a couple of days later it stopped working.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/6372715/85930492-d19dd180-b88a-11ea-98b9-a14475400bf9.png">

> [15:17:34.512] Logging Stopped.
[15:26:48.842] Logging Started...
[15:26:52.651] Microsoft ToDo[Script Filter] Queuing argument ''
[15:26:53.094] Microsoft ToDo[Script Filter] Script with argv '(null)' finished
[15:26:53.098] ERROR: Microsoft ToDo[Script Filter] Code 1: .
2020-06-27 15:26:52,994 mstodo       DEBUG    No auth in last 3600s, refreshing token
2020-06-27 15:26:53,018 workflow     ERROR    
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C5F221E0-97DB-474C-8A1D-4C4FD2273B0A/workflow/workflow.py", line 2073, in run
    func(self)
  File "alfred-mstodo-workflow.py", line 17, in main
    route(wf.args)
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C5F221E0-97DB-474C-8A1D-4C4FD2273B0A/mstodo/handlers/route.py", line 18, in route
    logged_in = is_authorised()
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C5F221E0-97DB-474C-8A1D-4C4FD2273B0A/mstodo/auth.py", line 57, in is_authorised
    return resolve_oauth_token(refresh_token=workflow().get_password(config.KC_REFRESH_TOKEN))
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C5F221E0-97DB-474C-8A1D-4C4FD2273B0A/workflow/workflow.py", line 2445, in get_password
    account, '-g')
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C5F221E0-97DB-474C-8A1D-4C4FD2273B0A/workflow/workflow.py", line 2813, in _call_security
    raise PasswordNotFound()
PasswordNotFound
[15:26:53.100] Microsoft ToDo[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Microsoft ToDo'</title><subtitle /><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by michalpanek** [comment]
Have you tried to reset the workflow? `_td-full-reset` and log to Microsoft account again to provide the password?

**Comment by kngan43** [comment]
Running the full reset solved the issue. Thanks!
