### ISSUE TITLE
"cannot concatenate 'str' and 'int' objects"

### ISSUE THREAD

**Issue by AlexHuckert** [johandebeurs/alfred-mstodo-workflow#24]
Hello,

I have the following error when trying to add a task using the workflow.

"cannot concatenate 'str' and 'int' objects"

Thanks for your help

**Comment by sandervdo** [comment]
I have the same behaviour, command I use is:

`td Mail Bob example docs`

Happy to provide any debug info if possible/necessary.

**Comment by johandebeurs** [comment]
Will need more detail on the actions that precede this as I can't reproduce. Please send the debug output from the workflow if you can reliably reproduce it

**Comment by DenniWittig** [comment]
Hi @johandebeurs
I also experience the issue described. 
Version 0.1.2, Enterprise Account. Worked under Big Sur, now with Monterey (M1) it does no longer.
See the Alfred Workflow Logs below:

> [16:38:31.653] Microsoft ToDo[Script Filter] Queuing argument ''
[16:38:32.012] Microsoft ToDo[Script Filter] Queuing argument ' '
[16:38:32.403] Microsoft ToDo[Script Filter] Script with argv '(null)' finished
[16:38:32.406] STDERR: Microsoft ToDo[Script Filter] .
2022-01-05 16:38:32,265 root         DEBUG    loading cached data: /Users/dennis.wittig/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.johandebeurs.alfred.mstodo/__workflow_latest_version.cpickle
2022-01-05 16:38:32,269 root         DEBUG    [sync] command cached: /Users/dennis.wittig/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.johandebeurs.alfred.mstodo/sync.argcache
2022-01-05 16:38:32,269 root         DEBUG    [sync] passing job to background runner: [u'/usr/bin/python', '/Users/dennis.wittig/OneDrive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B256A32E-3134-42FB-91E8-0193E3C286B4/workflow/background.pyo', 'sync']
.
16:38:32 workflow.py:2061 DEBUG    ---------- Microsoft ToDo (0.1.2) ----------
2022-01-05 16:38:32,395 root         DEBUG    [sync] background job started
2022-01-05 16:38:32,395 mstodo       INFO     Workflow response complete
2022-01-05 16:38:32,395 workflow     DEBUG    set last run version: 0.1.2
2022-01-05 16:38:32,395 workflow     DEBUG    ---------- finished in 0.194s ----------
[16:38:32.407] Microsoft ToDo[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Tasks &#8211; create a new task...</title><subtitle>Begin typing to add a new task</subtitle><subtitle mod="alt">&#8230;then edit it in the ToDo app    Begin typing to add a new task</subtitle><arg>--stored-query</arg><icon>icons/light/task.png</icon></item><item autocomplete=" :" valid="no"><title>Change folder</title><subtitle>Prefix the task, e.g. Automotive: </subtitle><icon>icons/light/list.png</icon></item><item autocomplete=" due " valid="no"><title>Set a due date</title><subtitle>"due" followed by any date-related phrase, e.g. due next Tuesday; due May 4</subtitle><icon>icons/light/calendar.png</icon></item><item autocomplete=" every " valid="no"><title>Make it a recurring task</title><subtitle>"every" followed by a unit of time, e.g. every 2 months; every year; every 4w</subtitle><icon>icons/light/recurrence.png</icon></item><item autocomplete=" remind me " valid="no"><title>Set a reminder</title><subtitle>"remind me" followed by a time and/or date, e.g. remind me at noon; r 10am; alarm 8:45p</subtitle><icon>icons/light/reminder.png</icon></item><item autocomplete=" *" valid="no"><title>Star</title><subtitle>End the task with * (asterisk)</subtitle><icon>icons/light/star.png</icon></item><item autocomplete="" valid="no"><title>Main menu</title><subtitle /><icon>icons/light/back.png</icon></item></items>
[16:38:33.688] Microsoft ToDo[Script Filter] Queuing argument ' T'
[16:38:33.821] Microsoft ToDo[Script Filter] Queuing argument ' Te'
[16:38:34.000] Microsoft ToDo[Script Filter] Queuing argument ' Tes'
[16:38:34.118] Microsoft ToDo[Script Filter] Queuing argument ' Test'
[16:38:34.446] Microsoft ToDo[Script Filter] Script with argv '(null)' finished
[16:38:34.452] STDERR: Microsoft ToDo[Script Filter] .
2022-01-05 16:38:34,376 root         DEBUG    loading cached data: /Users/dennis.wittig/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.johandebeurs.alfred.mstodo/__workflow_latest_version.cpickle
2022-01-05 16:38:34,376 mstodo       INFO     Workflow response complete
2022-01-05 16:38:34,376 workflow     DEBUG    set last run version: 0.1.2
2022-01-05 16:38:34,376 workflow     DEBUG    ---------- finished in 0.060s ----------
[16:38:34.455] Microsoft ToDo[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>Tasks &#8211; create a new task...</title><subtitle>Test</subtitle><subtitle mod="alt">&#8230;then edit it in the ToDo app    Test</subtitle><arg>--stored-query</arg><icon>icons/light/task.png</icon></item><item autocomplete=" : Test" valid="no"><title>Change folder</title><subtitle>Prefix the task, e.g. Automotive: Test</subtitle><icon>icons/light/list.png</icon></item><item autocomplete=" Test due " valid="no"><title>Set a due date</title><subtitle>"due" followed by any date-related phrase, e.g. due next Tuesday; due May 4</subtitle><icon>icons/light/calendar.png</icon></item><item autocomplete=" Test every " valid="no"><title>Make it a recurring task</title><subtitle>"every" followed by a unit of time, e.g. every 2 months; every year; every 4w</subtitle><icon>icons/light/recurrence.png</icon></item><item autocomplete=" Test remind me " valid="no"><title>Set a reminder</title><subtitle>"remind me" followed by a time and/or date, e.g. remind me at noon; r 10am; alarm 8:45p</subtitle><icon>icons/light/reminder.png</icon></item><item autocomplete=" Test *" valid="no"><title>Star</title><subtitle>End the task with * (asterisk)</subtitle><icon>icons/light/star.png</icon></item><item autocomplete="" valid="no"><title>Main menu</title><subtitle /><icon>icons/light/back.png</icon></item></items>
[16:38:35.076] Microsoft ToDo[Script Filter] Processing complete
[16:38:35.087] Microsoft ToDo[Script Filter] Passing output '--stored-query' to Run Script
[16:38:35.482] ERROR: Microsoft ToDo[Run Script] .
2022-01-05 16:38:35,411 workflow     ERROR    cannot concatenate 'str' and 'int' objects
Traceback (most recent call last):
  File "/Users/dennis.wittig/OneDrive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B256A32E-3134-42FB-91E8-0193E3C286B4/workflow/workflow.py", line 2073, in run
    func(self)
  File "alfred-mstodo-workflow.py", line 17, in main
    route(wf.args)
  File "/Users/dennis.wittig/OneDrive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B256A32E-3134-42FB-91E8-0193E3C286B4/mstodo/handlers/route.py", line 84, in route
    handler.commit(command, modifier)
  File "/Users/dennis.wittig/OneDrive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B256A32E-3134-42FB-91E8-0193E3C286B4/mstodo/handlers/new_task.py", line 168, in commit
    note=task.note)
  File "/Users/dennis.wittig/OneDrive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B256A32E-3134-42FB-91E8-0193E3C286B4/mstodo/api/tasks.py", line 170, in create_task
    req = api.post('me/outlook/taskFolders/' + taskfolder_id + '/tasks', params)
TypeError: cannot concatenate 'str' and 'int' objects
[16:38:35.503] Microsoft ToDo[Run Script] Processing complete
[16:38:35.504] Microsoft ToDo[Run Script] Passing output 'cannot concatenate 'str' and 'int' objects' to Post Notification

**Comment by bkuss** [comment]
got the same issue, m1pro macbook

**Comment by johandebeurs** [comment]
Unable to reproduce in the latest release
