### ISSUE TITLE
Login failed . return - HTTP ERROR 403

### ISSUE THREAD

**Issue by nephelo-xyz** [johandebeurs/alfred-mstodo-workflow#34]
The following is the debugging panel information：

Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nephelo-/data/soft/alfred-backup/Alfred.alfredpreferences/workflows/user.workflow.9DAAED63-79E1-4C38-8E7C-2EF4CA67D042/mstodo/auth.py", line 159, in await_token
    server = SocketServer.TCPServer(("", config.OAUTH_PORT), OAuthTokenResponseHandler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
2021-12-02 14:48:26,576 mstodo       INFO     Workflow response complete

**Comment by nephelo-xyz** [comment]
Add: 
macOS 12.0.1 Monterey
Alfred 4.6.1

**Comment by freedomlang** [comment]
@nephelo-xyz Turn of AirPlay Receiver may help

#20

**Comment by johandebeurs** [comment]
This is resolved in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0)
