### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by tenaz3** [johandebeurs/alfred-mstodo-workflow#4]
I did install and use `td` command, but nothing guide me to setup. Is there any permission or conflict I should be aware ?

<img width="915" alt="Screenshot 2020-05-05 at 14 17 32" src="https://user-images.githubusercontent.com/373955/81065223-5861ae00-8edb-11ea-98ee-65c63495c4bc.png">

**Comment by tenaz3** [comment]
Also when I use `td`  gets search:
<img width="603" alt="Screenshot 2020-05-06 at 13 25 00" src="https://user-images.githubusercontent.com/373955/81171629-fd908b00-8f9c-11ea-9bb5-8068d2f2a7df.png">

**Comment by sukhbsin** [comment]
Seeing the same behaviour

**Comment by johandebeurs** [comment]
Thanks - will investigate. What version of Alfred are you using?

**Comment by johandebeurs** [comment]
Fresh install from the mstodo.alfredworkflow in this GitHub repo into Alfred3 looks OK to me on a test just now. Can you provide a screenshot from the workflow config panel?

**Comment by johandebeurs** [comment]
Please try again - my hypothesis is that my dev logging was trying to reach an absolute path on my computer rather than relative. Have pushed a change which should fix for this

**Comment by sukhbsin** [comment]
Same result: 

[18:05:38.985] Logging Started...
[18:05:41.616] Microsoft ToDo[Script Filter] Queuing argument ''
[18:05:41.759] Microsoft ToDo[Script Filter] Script with argv '(null)' finished
[18:05:41.761] ERROR: Microsoft ToDo[Script Filter] Code 1: Traceback (most recent call last):
  File "alfred-mstodo-workflow.py", line 8, in <module>
    fileConfig('/Users/johan/Documents/Programming/Alfred workflows/alfred-mstodo-workflow/src/logging_config.ini')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'

**Comment by johandebeurs** [comment]
ok good to confirm that as the error. I missed out recompiling the workflow bundle prior to last push, have just rectified. LMK if this fixes the issue

**Comment by sukhbsin** [comment]
That seems to have fixed it, thanks
