### ISSUE TITLE
Not able to get sub-menus after typing "td" in Alfred 4

### ISSUE THREAD

**Issue by tshah95** [johandebeurs/alfred-mstodo-workflow#42]
When I type in "td", I'm getting two hits.  One is Microsoft To Do and the other one is Tableau.  I'm wondering if I have a keyword conflict.. Can someone please guide me in isolating/fixing the problem.  I'm very new to Alfred..
Using Alfred 4.7[1306] on Mac (Monterey 12.6) - Thanks !

**Comment by tshah95** [comment]
Folks, I'm trying to moving from Apple Reminders to Microsoft Todo.. any help would be greatly appreciated.  Thanks !

**Comment by johandebeurs** [comment]
This should be resolved in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0), but lmk if you still have issues

**Comment by bkuss** [comment]
I have this issue in Alfred 5.1.1 and release 0.2.0. Only Todoist app shows up in Alfred when i type "td".
I am on Ventura 13.1.

**Comment by johandebeurs** [comment]
Can you drop the logs from the debugger? My guess is that you don't have python3 available if its erroring out before displaying anything

**Comment by bkuss** [comment]
It was erroring out trying to load preferences from a previous version of the workflow:

[16:27:17.256] Microsoft ToDo[Script Filter] Queuing argument ''
[16:27:17.442] Microsoft ToDo[Script Filter] Script with argv '(null)' finished
[16:27:17.446] ERROR: Microsoft ToDo[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/bkuss/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.42232557-094B-40D9-B09C-A7C186CBD573/alfred_mstodo_workflow.py", line 9, in <module>
    from mstodo.handlers.route import route
  File "/Users/bkuss/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.42232557-094B-40D9-B09C-A7C186CBD573/mstodo/handlers/route.py", line 4, in <module>
    from mstodo import icons
  File "/Users/bkuss/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.42232557-094B-40D9-B09C-A7C186CBD573/mstodo/icons.py", line 27, in <module>
    _icon_path = f"icons/{icon_theme()}/"
                          ^^^^^^^^^^^^
  File "/Users/bkuss/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.42232557-094B-40D9-B09C-A7C186CBD573/mstodo/icons.py", line 18, in icon_theme
    prefs = Preferences.current_prefs()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bkuss/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.42232557-094B-40D9-B09C-A7C186CBD573/mstodo/models/preferences.py", line 52, in current_prefs
    cls._current_prefs = Preferences(wf.stored_data('prefs'))
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bkuss/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.42232557-094B-40D9-B09C-A7C186CBD573/workflow/workflow.py", line 1905, in stored_data
    raise ValueError(
ValueError: Unknown serializer `cpickle`. Register a corresponding serializer with `manager.register()` to load this data.

I was able to fix it by deleting the workflow data at
~/Library/Application Support/Alfred/Workflow Data/com.johandebeurs.alfred.mstodo

**Comment by johandebeurs** [comment]
Great, in that case for reference for others who come across this, it should also be solvable by running `_td-reset` in alfred to clear the caches
