### ISSUE TITLE
I can't seem to get it to work

### ISSUE THREAD

**Issue by JustCrazyer** [johandebeurs/alfred-mstodo-workflow#5]
Here is the error message in the debugging panel.
`[21:13:18.004] Microsoft ToDo[Script Filter] Queuing argument ' '
[21:13:18.153] Microsoft ToDo[Script Filter] Script with argv '(null)' finished
[21:13:18.160] ERROR: Microsoft ToDo[Script Filter] Code 1: Traceback (most recent call last):
  File "alfred-mstodo-workflow.py", line 8, in <module>
    fileConfig('/Users/johan/Documents/Programming/Alfred workflows/alfred-mstodo-workflow/src/logging_config.ini')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'`

**Comment by JustCrazyer** [comment]
Modify File "alfred-mstodo-workflow.py", **_johan_** line 8, in <module> fileConfig ('/Users/ **_johan_** / Documents /

Still not working
